### PR TITLE
Add ssh_private_key configuration option

### PR DESCRIPTION
**Pull request by machacekondra**

### CODE REVIEW

**Comment by machacekondra** [comment]
cc @mwperina

**Comment by machacekondra** [comment]
Hello @pcuzner @jmolmo can you please review/merge if all is OK? Thank you!

**Comment by jmolmo** [comment]
LGTM

**Comment by pcuzner** [comment]
@machacekondra sorry for missing the point - but there's no description with this PR. What is it you want to do? Is the goal to provide an override for the ssh key that you embed in the project folder?

**Comment by machacekondra** [comment]
Exactly. In the oVirt project we create the `ssh_key` on our own and the location is for many versions the same, and we don't want to copy it on other places, we want to have it on single location and so this PR add an option to change the location of the ssh_key.

**Comment by pcuzner** [comment]
Cool - thanks!

**Pull request merged**
