### PR TITLE
Add spec file without systemd unit file

### PR DESCRIPTION
**Pull request by machacekondra**

### CODE REVIEW

**Comment by machacekondra** [comment]
cc @mwperina

**Comment by machacekondra** [comment]
Hello @pcuzner @jmolmo can you please review/merge if all is OK? Thank you!

**Comment by jmolmo** [comment]
In misc/packaging we have this file. Why are you adding this file?
Can you modify that file instead adding a new one in a different location?

**Comment by machacekondra** [comment]
@jmolmo This one is quite different. Your spec file is used for flask prepared. But this spec file is used for apache preprepared. User can just do the following and it will work on apache:

```
Listen 5001
<VirtualHost _default_:5001>
    LogLevel debug
    WSGIDaemonProcess runner user=o group=o threads=2
    WSGIProcessGroup runner
    WSGIScriptAlias / /var/www/runner/runner.wsgi
    CustomLog "logs/ansible_runner_log" "%h %l %u %t \"%r\" %>s %b"
    ErrorLog "logs/ansible_runner_error_log"
</VirtualHost>
```

If he copies `wsgi.py` to `/var/www/runner/runner.wsgi`.

**Comment by jmolmo** [comment]
Ok. A different spec file, implies a different kind of deployment. Can you move it to "misc/packaging/apache"? Include the clarification you write in this pr in a text file in the new folder will be also a good idea.

**Comment by machacekondra** [comment]
@jmolmo Thank you for review. I've moved the spec file and added README file.

**Pull request merged**
