### PR TITLE
UBI8 Image Rebase

### PR DESCRIPTION
**Pull request by usrbinkat**
Add [UBI8](https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image) based `Dockerfile.ubi8` for testing.

Image built successfully [here](https://github.com/ContainerCraft/ansible-runner-service/runs/1234467730?check_suite_focus=true)

Image is available for testing with:
```
 podman pull quay.io/containercraft/ansible-runner-service
```
For comparison, review difference of 41 security vulnerability scan hits in UBI8's favor on Quay Claire results here:
https://quay.io/repository/containercraft/ansible-runner-service?tab=tags

### CODE REVIEW

**Review by mwperina — APPROVED** [review]
Looks good to me

**Comment by mwperina** [comment]
Juan/Paul, are you OK with this new image?

@jmolmo @pcuzner

**Review by mnecas — APPROVED** [review]
LGTM

**Comment by ktdreyer** [comment]
Are those vulnerabilities coming from the `docker.io/library/centos:7` base image?

**Review by pcuzner — APPROVED** [review]
LGTM

**Comment by usrbinkat** [comment]
> Are those vulnerabilities coming from the `docker.io/library/centos:7` base image?

@ktdreyer there are 2 key differences in the source of vulns.

1. the ubi image likely triggers fewer errors, We could push a centos:8 image to quay and evaluate the delta between ubi:8 and centos:8

2. the ubi dockerfile is rhel 8.2 based whereas the centos dockerfile is built on the 7.x release

```
kmorgan@mprcs:~$ podman run -it --rm registry.access.redhat.com/ubi8/ubi:latest cat /etc/redhat-release
Red Hat Enterprise Linux release 8.2 (Ootpa)
```

**Pull request merged**
