### PR TITLE
Add support override inventory hosts by parameter

### PR DESCRIPTION
**Pull request by machacekondra**
This PR add support to override invetory hosts by `hosts` HTTP POST parameter

### CODE REVIEW

**Comment by jmolmo** [comment]
The hosts included in the inventory has been added after checking that the connection with these servers is possible and therefore Ansible Playbooks can be executed in them. 
So this modification opens the door to have playbook executions with hosts connection errors. Or even executions on unexpected hosts.

I think that is good to have a "protocol" to use the service, first you need to "register" the external host. (it is added to the inventory and it is reachable and usable, so somebody has previpously granted this access ), the "registration" process ( add the host to the inventory) works also like a "double check" about the access to the external host. 

Maybe i do not understand very well the motivation of this change, but in my opinion it adds a certain level of risk.

**Comment by machacekondra** [comment]
Ok, that makes sense. I just don't wanna store `ssh_private_key` in `env/ssh_key`, I already have ssh key somewhere else. So do you think it would make sense to add to `hosts/{host_name}/groups/{group_name}` paramter which would override the `env/ssh_key`?

**Comment by jmolmo** [comment]
> Ok, that makes sense. I just don't wanna store `ssh_private_key` in `env/ssh_key`, I already have ssh key somewhere else. So do you think it would make sense to add to `hosts/{host_name}/groups/{group_name}` paramter which would override the `env/ssh_key`?

Probably you are going to use always the same certificate for connecting with different external hosts. To use a parameter to pass always the same information does not seem very much operative.

In this case i think that probably is more adequate to add an specific configuration setting to hold the folder where the private/pub key files are going to be stored.
In this moment it is used the variable "playbooks_root_dir" to get the folder where the "env" folder is placed, and the certificates must be in this folder.

In this way you can configure the service to use the keys you want in the place you want.

**Comment by machacekondra** [comment]
ok, thank you!

**Pull request closed without merging**
